### ISSUE TITLE
PRÁCTICA DE HILOS

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/practica-de-hilos-Eva155#2]
[PRÁCTICA DE HILOSS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Eva155/files/6511052/PRACTICA.DE.HILOSS.pdf)

**Comment by Abraham890** [comment]
Calificación obtenida: 20/20
Califico: Abraham Reyes Ortiz

**Comment by josealfredo79** [comment]
Bien hecho y revisado
